# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
# config/services.yaml

parameters:

services:
    # Configuration par défaut pour tous les services
    _defaults:
        autowire: true      # Injection automatique des dépendances
        autoconfigure: true # Configure automatiquement les services

    # Enregistre tous les fichiers dans src/ comme services
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    # Configuration spéciale pour PasskeyAuthService
    # On lui passe les variables d'environnement manuellement
    App\Service\PasskeyAuthService:
        arguments:
            $rpName: '%env(WEBAUTHN_RP_NAME)%'
            $rpId: '%env(APP_DOMAIN)%'